apiVersion: v1
kind: Service
metadata:
 name: fastapi-service
spec:
 type: NodePort
 selector:
   app: fastapi
 ports:
   - protocol: TCP
     port: 8002       # port widoczny w Kubernetes
     targetPort: 8000 # port w kontenerze
     nodePort: 31665  # port na nodzie
